version: '3'
services:
  db:
    image: mysql/mysql-server:5.7
    ports: 
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_ROOT_HOST: "%"
    volumes: 
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db
    links: 
      - db
  web:
    image: faelp22/lap:0.2.1
    command:  bash -c "chmod -R 777 /var/www/html"
    ports:
      - 8000:80
    depends_on: 
      - db
    links: 
      - db
    volumes: 
      - ./www:/var/www/html
